### ISSUE TITLE
Continue development

### ISSUE THREAD

**Issue by lazyfrosch** [NETWAYS/check_hp_msa#1]
This plugin was prototyped during consulting with a customer.

We still need to add modes for:
* vdisks
* pools
* disk-groups?
* volumes
* controllers
* enclosures
* power-supplies
* fans
* ports

If you are interested in sponsoring, please contact me: markus.frosch@netways.de

ref/NC/703245

**Comment by martialblog** [comment]
Currently not actively development on this plugin. Can be reopened if necessary
