### ISSUE TITLE
Possible incompatibility issue with newer HPE SAN systems

### ISSUE THREAD

**Issue by geotekberlin** [NETWAYS/check_hp_msa#3]
This script works fine with HP MSA 2050 SA, but on a brand new HPE MSA 2060 SAN output is
`  [CRITICAL] login failed: Error: Authentication Unsuccessful`
I double checked the credentials and even the Admin credentials won't work even though login is possible to the HP Web GUIl

Could it be that HPE has changed API specifications on this new model so that this wonderful check script won't work any more?

**Comment by martialblog** [comment]
Hi, yes might be that the authentication method has changed. 

Could also be that the endpoint or authentication type has changed.

https://github.com/NETWAYS/check_hp_msa/blob/main/check_hp_msa.py#L98

We're accepting Pull requests if you want to extend the plugin.

**Comment by geotekberlin** [comment]
Hi Markus,

thank you for your quick reply. Unfortunately my programming skills are 
very limited and have no experience at all with Python or how to make a 
GitHub Pull request.

Is there any hope that your HP script will be updated to support current 
SANs in the near future? The only help that I could offer would be to 
alpha- or beta test new builds.

Best Regards,

Martin


------ Originalnachricht ------
Von "Markus Opolka" ***@***.***>
An "NETWAYS/check_hp_msa" ***@***.***>
Cc "geotekberlin" ***@***.***>; "Author" ***@***.***>
Datum 12.10.2023 18:13:20
Betreff Re: [NETWAYS/check_hp_msa] Possible incompatibility issue with 
newer HPE SAN systems (Issue #3)

**Comment by martialblog** [comment]
It's difficult to say at this point. I can have a look at the HP API specs and see if there's something I can work with. Otherwise it's really tricky to debug/fix without the actual API

**Comment by geotekberlin** [comment]
Hi Markus,

I just saw that the Centreon had the same issue: Starting with HPE MSA 
2060, the API authentication failed. Solution was to add a new option 
--digest-sha256

https://github.com/centreon/centreon-plugins/pull/3907

Maybe this helps

Best Regards,

Martin



------ Originalnachricht ------
Von "Markus Opolka" ***@***.***>
An "NETWAYS/check_hp_msa" ***@***.***>
Cc "geotekberlin" ***@***.***>; "Author" ***@***.***>
Datum 16.10.2023 16:30:40
Betreff Re: [NETWAYS/check_hp_msa] Possible incompatibility issue with 
newer HPE SAN systems (Issue #3)

**Comment by martialblog** [comment]
Interesting. Yeah that might work. Thanks for the hint
